export const pricingContent = {
  eyebrow: "TRANSPARENT VALUE ARCHITECTURE",
  headline: "Predictable Investment. Compounding Return.",
  subhead:
    "We don't bill vague hourly retainers. Choose between turnkey sprint deployments or continuous dedicated AI consulting partnerships.",
  tiers: [
    {
      id: "growth-sprint",
      name: "Growth Automation Sprint",
      subtitle: "For founders & practices needing rapid lead capture and automated booking.",
      price: "₹65,000",
      period: "one-time investment",
      badge: "RAPID DEPLOYMENT",
      popular: false,
      features: [
        "Custom 24/7 WhatsApp AI Booking Agent",
        "CRM Sync (Notion, Airtable, or HubSpot)",
        "Instant Lead Notification Webhook Engine",
        "1 High-Converting Landing Page Architecture",
        "Full 100% Code & Workflow IP Handover",
        "14-Day Delivery SLA + 30-Day Support",
      ],
      cta: "Deploy Growth Sprint",
    },
    {
      id: "enterprise-transformation",
      name: "Autonomous Enterprise Engine",
      subtitle: "Our flagship practice: Full-stack AI agent network + Next.js 15 web flagship.",
      price: "₹1,45,000",
      period: "turnkey system build",
      badge: "MOST POPULAR",
      popular: true,
      features: [
        "Multi-Agent AI Workflow (Claude 3.5 + GPT-4o)",
        "Bespoke Next.js 15 Web Flagship (SSR + Tailwind)",
        "Official WhatsApp Business API Gateway",
        "Deep CRM Auto-Enrichment (Apollo/LinkedIn)",
        "Technical SEO & Schema Semantic Engine",
        "Comprehensive Automated Inbound & Outbound Logic",
        "Executive Dashboard & Telemetry Setup",
        "21-Day Delivery SLA + 60-Day Partner Governance",
      ],
      cta: "Schedule Architecture Call",
    },
    {
      id: "fractional-partner",
      name: "Fractional AI Systems Partner",
      subtitle: "Dedicated ongoing engineering, model fine-tuning, and priority expansion.",
      price: "₹45,000",
      period: "per month retainer",
      badge: "CONTINUOUS SCALE",
      popular: false,
      features: [
        "Dedicated Lead AI Engineer & Architect",
        "Continuous Pipeline Optimization & Prompt Tuning",
        "Unlimited New Workflow Builds (1 active at a time)",
        "99.9% Uptime Monitoring & Rapid Incident SLA",
        "Quarterly Executive AI Growth Reviews",
        "Zero Long-Term Lock-in (Cancel anytime)",
      ],
      cta: "Engage Fractional Partner",
    },
  ],
};
